Fixed several bugs where 'sizeof' applied to pointer instead of underlying struct.
Found with Clang - example warning:
  ../kernel/syscall.c:411:27: error: 'memset' call operates on objects of type 'struct cte' while the size is based on a different type 'struct cte *' [-Werror,-Wsizeof-pointer-memaccess]
     memset(cte, 0, sizeof(cte));
            ~~~            ^~~
  ../kernel/syscall.c:411:27: note: did you mean to dereference the argument to 'sizeof' (and multiply it by the number of elements)?
     memset(cte, 0, sizeof(cte));
                           ^~~