kernel: Implement strstr().
Compilation for armv7 failed with the following error:

../kernel/string.c:33:1: error: function might be candidate for attribute
'noreturn' [-Werror=suggest-attribute=noreturn]

Instead of adding the attribute, I provided a simple implementation.