Added get_phyaddr_cap() that requests the Physical address caps from the monitor using a RPC call.
This currently breaks in acpica, not sure why.
ERROR: acpi.0 in AcpiOsMapMemory() ../usr/acpi/acpica_osglue.c:549
ERROR: after revoke, retype AcpiOsMapMemory(1073731120, 4096)
Failure: (         kernel) Capability already has descendants or siblings [SYS_ERR_REVOKE_FIRST]
Assertion failed on core 0 in acpi: r == 0, function AcpiOsMapMemory, file ../usr/acpi/acpica_osglue.c, line 550.