armv7: use A9 timer functions only in pandaboard
These functions are only defined for pandaboard:
 collect2: ld terminated with signal 11 [Segmentation fault]
 ./armv7/kernel/arch/armv7/syscall.o: In function `sys_syscall':
 syscall.c:(.text+0x9ac): undefined reference to `gt_read_high'
 syscall.c:(.text+0x9c0): undefined reference to `gt_read_low'

Guard them with an #if for now.