Disable -Wshadow for thcidctest
The DO_FINISH macro (defined in <thc/thc.h>) is used in nested scopes.  Once
expaned it defines a local variable multiple times which aborts the build:

  ../include/thc/thc.h:54:14: error: declaration of '_fb' shadows a previous local [-Werror=shadow-compatible-local]
       finish_t _fb;                                                       \
                ^
  ../include/thc/thc.h:61:10: note: in definition of macro 'DO_FINISH__'
       do { _CODE } while (0);                                             \
            ^
  ../usr/tests/thcidctest/thcidctest.c:95:5: note: in expansion of macro 'DO_FINISH'
       DO_FINISH({
       ^
  ../include/thc/thc.h:40:26: note: in expansion of macro 'DO_FINISH__'
   #define DO_FINISH(_CODE) DO_FINISH__(__,_CODE,0)
                            ^
  ../usr/tests/thcidctest/thcidctest.c:136:7: note: in expansion of macro 'DO_FINISH'
         DO_FINISH({
         ^
  ../include/thc/thc.h:54:14: error: shadowed declaration is here [-Werror=shadow-compatible-local]
       finish_t _fb;                                                       \
                ^
  ../include/thc/thc.h:40:26: note: in expansion of macro 'DO_FINISH__'
   #define DO_FINISH(_CODE) DO_FINISH__(__,_CODE,0)
                            ^
  ../usr/tests/thcidctest/thcidctest.c:95:5: note: in expansion of macro 'DO_FINISH'
       DO_FINISH({
       ^

Signed-off-by: Zaheer Chothia <zchothia@inf.ethz.ch>